global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: downloader-bot
    static_configs:
      - targets: ['app:8081']
  - job_name: redis
    static_configs:
      - targets: ['redis_exporter:9121']