spring:
  docker:
    compose:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info
  endpoint:
    prometheus:
      access: unrestricted
  metrics:
    tags:
      application: ${spring.application.name}
    enable:
      jvm: true
      system: true
      process: true
