name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  checks: write
  pull-requests: write

env:
  IS_RP: ${{ github.actor == 'github-actions[bot]' && (startsWith(github.head_ref, 'release-please--') || startsWith(github.ref_name, 'release-please--')) }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fast-pass for release-please PR
        if: env.IS_RP == 'true'
        run: echo "Release-please PR detected — marking build as passed without heavy steps."

      - name: Full build
        if: env.IS_RP != 'true'
        uses: ./.github/actions/gradle-build
