name: Lint PR

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read
  pull-requests: read
  statuses: write

jobs:
  semantic-pr:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          scopes: |
            main
            bot
            gateway
            app
            domain
            ratelimit
            core
            logging
            infra
            build
            ci
            docker
            docs
            test
            config
            scripts
          ignoreLabels: |
            autorelease: pending
          wip: true
